spring:
  application:
    name: spring-cloud-stream-transaction
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_cloud_stream_transaction
    username: ${USER}
    password: 123123
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
  cloud:
    stream:
      bindings:
        created-contact-output:
          destination: streaming.spring-cloud-stream-transaction.contact.created
        created-contact-input:
          destination: streaming.spring-cloud-stream-transaction.contact.created
          group: ${spring.application.name}
      kafka:
        binder:
          transaction:
            transaction-id-prefix: "kafkatx-"
            producer:
              configuration:
                retries: 1
                acks: all
