logging:
  file: application.log
spring:
  application:
    name: poc-cucumber-mvc
  datasource:
    url: jdbc:postgresql://localhost:5432/poc_cucumber_mvc
    username: lferreira
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true