spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poc_spring_data_jpa
    username: ${USER}
    password: 123123
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
#    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
