spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poc_auditing
    username: ${USER}
    password: 123123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
      org.hibernate.envers:
        audit_table_suffix: "_HISTORY"
        revision_field_name: "REVISION"
        revision_type_field_name: "REVISION_TYPE"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
